In [1]:
import pandas as pd
import numpy as np

In [2]:
url="https://raw.githubusercontent.com/RavinduPathirana28/Laptop_Price_Predictor/refs/heads/main/Model/laptop_price.csv"
data=pd.read_csv(url)
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [3]:
data.shape

(1303, 12)

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   str
 8   Gpu               1303 non-null   str
 9   OpSys             1303 non-null   str
 10  Weight            1303 non-null   str
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), str(9)
memory usage: 122.3 KB

In [5]:
data.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [6]:
print(data['Ram'].dtype)
print(data['Ram'].head())

str
0     8GB
1     8GB
2     8GB
3    16GB
4     8GB
Name: Ram, dtype: str

In [7]:
print(data['Weight'].dtype)
print(data['Weight'].head())

str
0    1.37kg
1    1.34kg
2    1.86kg
3    1.83kg
4    1.37kg
Name: Weight, dtype: str

In [8]:
#changing the data types of Ram and Weigth to continues values 
data['Ram']=data['Ram'].str.replace('GB','').astype('int64')
data['Weight']=data['Weight'].str.replace('kg','').astype('float64')

In [38]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   str
 2   Product           1303 non-null   str
 3   TypeName          1303 non-null   str
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   str
 6   Cpu               1303 non-null   str
 7   Ram               1303 non-null   int64
 8   Gpu               1303 non-null   str
 9   OpSys             1303 non-null   str
 10  Weight            1303 non-null   float64
 11  Price_euros       1303 non-null   float64
dtypes: float64(3), int64(2), str(7)
memory usage: 122.3 KB

In [9]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60

In [10]:
# Correlation of numeric features
data.select_dtypes(include='number').corr()['Price_euros']

laptop_ID      0.067830
Inches         0.068197
Ram            0.743007
Weight         0.210370
Price_euros    1.000000
Name: Price_euros, dtype: float64

In [11]:
data['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [12]:
def add_company(inpt):
    if inpt=='Samsung' or inpt=='Razer' or inpt=='Mediacom' or inpt=='Microsoft' or inpt=='Xiaomi' or inpt=='Vero' or inpt=='Chuwi' or inpt=='Google' or inpt=='Fujitsu' or inpt=='LG' or inpt=='Huawei':
        return 'Other'
    else:
        return inpt
data['Company']=data['Company'].apply(add_company)

In [13]:
data['Company'].value_counts()

Company
Dell       297
Lenovo     297
HP         274
Asus       158
Acer       103
MSI         54
Other       51
Toshiba     48
Apple       21
Name: count, dtype: int64

In [14]:
data['Product'].value_counts()

Product
XPS 13                                30
Inspiron 3567                         29
250 G6                                21
Legion Y520-15IKBN                    19
Vostro 3568                           19
                                      ..
X541NA-GO020T (N3350/4GB/1TB/W10)      1
Rog G752VT-GC073T                      1
B51-80 (i7-6500U/8GB/1008GB/Radeon     1
GE62 Apache                            1
Yoga 500-14IBD                         1
Name: count, Length: 618, dtype: int64

In [15]:
data['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [16]:
data['ScreenResolution'].value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
IPS Panel 1366x768                                 7
Touchscreen 2560x1440                              7
4K Ultra HD 3840x2160                              7
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Touchscreen 2560x1440                    5
1440x900                                           4
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
IPS Panel 2560x1440                                4
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Quad HD+ 2560x1440                       3
IPS Panel Touchscreen 1366x768                     3
1920x1080                                          3
Quad HD+ 3200x1800                                 3
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
Touchscreen / Quad HD+ 3200x1800                   1
IPS Panel Full HD 1366x768                         1
IPS Panel Full HD 2560x1440                        1
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [17]:
data['Touchscreen']=data['ScreenResolution'].apply(lambda x:1 if 'Touchscreen' in x else 0)
data['IPS']=data['ScreenResolution'].apply(lambda x:1 if 'IPS' in x else 0)

In [18]:
data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1

In [70]:
data['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz              190
Intel Core i7 7700HQ 2.8GHz             146
Intel Core i7 7500U 2.7GHz              134
Intel Core i7 8550U 1.8GHz               73
Intel Core i5 8250U 1.6GHz               72
                                       ...
Intel Core i5 7200U 2.7GHz                1
Intel Pentium Dual Core 4405Y 1.5GHz      1
Intel Core M 6Y54 1.1GHz                  1
Samsung Cortex A72&A53 2.0GHz             1
AMD E-Series 9000 2.2GHz                  1
Name: count, Length: 118, dtype: int64

In [19]:
data['cpu_name']=data['Cpu'].apply(lambda x: "".join(x.split()[0:3]))
data['cpu_name'].value_counts()

cpu_name
IntelCorei7               527
IntelCorei5               423
IntelCorei3               136
IntelCeleronDual           80
IntelPentiumQuad           27
IntelCoreM                 19
AMDA9-Series9420           12
AMDA6-Series9220            8
IntelCeleronQuad            8
AMDA12-Series9720P          7
IntelAtomx5-Z8350           5
IntelAtomx5-Z8550           4
AMDA8-Series7410            4
AMDRyzen1700                3
IntelPentiumDual            3
AMDA9-Series9410            3
AMDE-SeriesE2-9000e         2
IntelXeonE3-1505M           2
AMDA10-SeriesA10-9620P      2
AMDA6-SeriesA6-9220         2
AMDA10-Series9600P          2
AMDA10-Series9620P          2
AMDE-Series7110             2
AMDA9-SeriesA9-9420         2
IntelXeonE3-1535M           2
IntelAtomX5-Z8350           2
IntelAtomx5-Z8300           1
AMDE-SeriesE2-6110          1
AMDFX9830P                  1
AMDE-Series6110             1
AMDE-Series9000e            1
AMDRyzen1600                1
AMDE-SeriesE2-9000          1
AMDA6-Series7310            1
IntelAtomZ8350              1
AMDA12-Series9700P          1
AMDA4-Series7210            1
AMDFX8800P                  1
SamsungCortexA72&A53        1
AMDE-Series9000             1
Name: count, dtype: int64

In [20]:
def set_processor(c_name):
    if c_name=='IntelCorei7' or c_name=='IntelCorei5'or c_name=='IntelCorei3':
        return c_name
    else:
        if c_name.split()[0]=='AMD':
            return 'AMD'
        else:
            return 'Other'
data['cpu_name']=data['cpu_name'].apply(set_processor)

In [21]:
data['cpu_name'].value_counts()

cpu_name
IntelCorei7    527
IntelCorei5    423
Other          217
IntelCorei3    136
Name: count, dtype: int64

In [81]:
data['Gpu'].value_counts()

Gpu
Intel HD Graphics 620      281
Intel HD Graphics 520      185
Intel UHD Graphics 620      68
Nvidia GeForce GTX 1050     66
Nvidia GeForce GTX 1060     48
                          ...
Nvidia Quadro M500M          1
AMD Radeon R7 M360           1
Nvidia Quadro M3000M         1
Nvidia GeForce 960M          1
ARM Mali T860 MP4            1
Name: count, Length: 110, dtype: int64

In [22]:
data['gpu_name']=data['Gpu'].apply(lambda x:"".join(x.split()[0:1]))
data['gpu_name'].value_counts()

gpu_name
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [23]:
data.shape

(1303, 16)

In [24]:
data=data[data['gpu_name'] !='ARM']
data.shape

(1302, 16)

In [25]:

data.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS,cpu_name,gpu_name
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,0,1,IntelCorei5,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,IntelCorei5,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,575.00,0,0,IntelCorei5,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,2537.45,0,1,IntelCorei7,AMD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,0,1,IntelCorei5,Intel

In [26]:
data['OpSys'].value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         26
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [27]:
def set_os(os):
    if os=='Windows 10' or os=='Windows 7' or os=='Windows 10 S':
        return 'Windows'
    elif os=='Linux':
        return os
    elif os=='macOS' or os=='Mac OS X':
        return 'Mac'
    else:
        return 'Other'
data['OpSys']=data['OpSys'].apply(set_os)
data['OpSys'].value_counts()

OpSys
Windows    1125
Other        94
Linux        62
Mac          21
Name: count, dtype: int64

In [28]:
data=data.drop(columns=['laptop_ID','ScreenResolution','Cpu','Gpu','Inches','Product'])
data.head()

,Company,TypeName,Ram,OpSys,Weight,Price_euros,Touchscreen,IPS,cpu_name,gpu_name
0,Apple,Ultrabook,8,Mac,1.37,1339.69,0,1,IntelCorei5,Intel
1,Apple,Ultrabook,8,Mac,1.34,898.94,0,0,IntelCorei5,Intel
2,HP,Notebook,8,Other,1.86,575.00,0,0,IntelCorei5,Intel
3,Apple,Ultrabook,16,Mac,1.83,2537.45,0,1,IntelCorei7,AMD
4,Apple,Ultrabook,8,Mac,1.37,1803.60,0,1,IntelCorei5,Intel

In [29]:
#data converting to numerical
data = pd.get_dummies(data, dtype=int)
data.head()

,Ram,Weight,Price_euros,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,OpSys_Mac,OpSys_Other,OpSys_Windows,cpu_name_IntelCorei3,cpu_name_IntelCorei5,cpu_name_IntelCorei7,cpu_name_Other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,1339.69,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
1,8,1.34,898.94,0,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2,8,1.86,575.00,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,0,1,0
3,16,1.83,2537.45,0,1,0,1,0,0,0,...,1,0,0,0,0,1,0,1,0,0
4,8,1.37,1803.60,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [30]:
data.info

<bound method DataFrame.info of       Ram  Weight  Price_euros  Touchscreen  IPS  Company_Acer  Company_Apple  \
0       8    1.37      1339.69            0    1             0              1
1       8    1.34       898.94            0    0             0              1
2       8    1.86       575.00            0    0             0              0
3      16    1.83      2537.45            0    1             0              1
4       8    1.37      1803.60            0    1             0              1
...   ...     ...          ...          ...  ...           ...            ...
1298    4    1.80       638.00            1    1             0              0
1299   16    1.30      1499.00            1    1             0              0
1300    2    1.50       229.00            0    0             0              0
1301    6    2.19       764.00            0    0             0              0
1302    4    2.20       369.00            0    0             0              0

      Company_Asus  Company_Dell  Company_HP  ...  OpSys_Mac  OpSys_Other  \
0                0             0           0  ...          1            0
1                0             0           0  ...          1            0
2                0             0           1  ...          0            1
3                0             0           0  ...          1            0
4                0             0           0  ...          1            0
...            ...           ...         ...  ...        ...          ...
1298             0             0           0  ...          0            0
1299             0             0           0  ...          0            0
1300             0             0           0  ...          0            0
1301             0             0           1  ...          0            0
1302             1             0           0  ...          0            0

      OpSys_Windows  cpu_name_IntelCorei3  cpu_name_IntelCorei5  \
0                 0                     0                     1
1                 0                     0                     1
2                 0                     0                     1
3                 0                     0                     0
4                 0                     0                     1
...             ...                   ...                   ...
1298              1                     0                     0
1299              1                     0                     0
1300              1                     0                     0
1301              1                     0                     0
1302              1                     0                     0

      cpu_name_IntelCorei7  cpu_name_Other  gpu_name_AMD  gpu_name_Intel  \
0                        0               0             0               1
1                        0               0             0               1
2                        0               0             0               1
3                        1               0             1               0
4                        0               0             0               1
...                    ...             ...           ...             ...
1298                     1               0             0               1
1299                     1               0             0               1
1300                     0               1             0               1
1301                     1               0             1               0
1302                     0               1             0               1

      gpu_name_Nvidia
0                   0
1                   0
2                   0
3                   0
4                   0
...               ...
1298                0
1299                0
1300                0
1301                0
1302                0

[1302 rows x 31 columns]>

In [32]:
data.shape

(1302, 31)

In [34]:
x=data.drop('Price_euros',axis=1)
x.head()

,Ram,Weight,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,Company_Lenovo,...,OpSys_Mac,OpSys_Other,OpSys_Windows,cpu_name_IntelCorei3,cpu_name_IntelCorei5,cpu_name_IntelCorei7,cpu_name_Other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,0,1,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
1,8,1.34,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2,8,1.86,0,0,0,0,0,0,1,0,...,0,1,0,0,1,0,0,0,1,0
3,16,1.83,0,1,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
4,8,1.37,0,1,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [37]:
y=data['Price_euros']
data.head()

,Ram,Weight,Price_euros,Touchscreen,IPS,Company_Acer,Company_Apple,Company_Asus,Company_Dell,Company_HP,...,OpSys_Mac,OpSys_Other,OpSys_Windows,cpu_name_IntelCorei3,cpu_name_IntelCorei5,cpu_name_IntelCorei7,cpu_name_Other,gpu_name_AMD,gpu_name_Intel,gpu_name_Nvidia
0,8,1.37,1339.69,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
1,8,1.34,898.94,0,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2,8,1.86,575.00,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,0,1,0
3,16,1.83,2537.45,0,1,0,1,0,0,0,...,1,0,0,0,0,1,0,1,0,0
4,8,1.37,1803.60,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [40]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y ,test_size=0.25)
x_train.shape

(976, 30)

In [44]:
def model_acc(model):
    model.fit(x_train,y_train)
    acc=model.score(x_test,y_test)
    print(str(model)+'-->'+str(acc))

In [46]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model_acc(lr)

LinearRegression()-->0.7021618633508353

In [48]:
from sklearn.linear_model import Lasso
ls=Lasso()
model_acc(ls)

Lasso()-->0.7007967938810294

In [51]:
from sklearn.ensemble import RandomForestRegressor 
rfr=RandomForestRegressor()
model_acc(rfr)

RandomForestRegressor()-->0.7374893931233653

In [62]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
model_acc(dt)

DecisionTreeRegressor()-->0.6267413483429634

In [68]:
from sklearn.model_selection import GridSearchCV
parameters={
    'n_estimators':[10,50,100],
    'criterion':['squared_error','absolute_error','poisson']
}
grid_obj=GridSearchCV(estimator=rfr, param_grid=parameters)
grid_fit=grid_obj.fit(x_train,y_train)
best_model=grid_fit.best_estimator_
best_model

RandomForestRegressor(criterion='absolute_error')

In [69]:
best_model.score(x_test,y_test)

0.7475031536139606

In [70]:
import pickle 
with open ('predictor.pickle','wb') as file:
    pickle.dump(best_model, file)

In [1]:
x_train.columns

NameError: name 'x_train' is not defined